---
- name: "Create mambo tiles directory"
  file: path=/opt/mambo/tiles state=directory mode=0755
- name: "Create mambo assets directory"
  file: path=/opt/mambo/assets state=directory mode=0755
- name: "Create mambo resources directory"
  file: path=/opt/mambo/imagery state=directory mode=0755
- name: "Create mambo orthophoto tif tmp directory"
  file: path=/opt/mambo/imagery/tmp_orthophoto_tif state=directory mode=0755
- name: "Create mambo orthophoto texturing tmp directory"
  file: path=/opt/mambo/imagery/tmp_orthophoto_texturing state=directory mode=0755
- name: "Create mambo drone imagery tmp directory"
  file: path=/opt/mambo/imagery/tmp_drone_imgs state=directory mode=0755
- name: "Create mambo conf directory"
  file: path=/etc/mambo state=directory mode=0755
- name: Copy mambo settings files for sensor-api
  copy: src=etc/sensor-api/ dest=/etc/mambo/sensor-api/
- name: Copy mambo settings files for tile-api
  copy: src=etc/tile-api/ dest=/etc/mambo/tile-api/  
- name: Copy mambo settings files for dashboard-www
  copy: src=etc/dashboard-www/ dest=/etc/mambo/dashboard-www/
- name: Copy mambo docker-compose file
  copy: src=mambo.yml dest=/opt/mambo/mambo.yml
- name: Copy mambo service
  copy: src=mambo.service dest=/etc/systemd/system/mambo.service
- name: Copy mambo docker image opendronemapd
  copy: src=opendronemapd/ dest=/opt/mambo/opendronemapd/ directory_mode=0755
- name: Copy mambo docker images gdal2tiles
  copy: src=gdal2tiles/ dest=/opt/mambo/gdal2tiles/ directory_mode=0755
- name: Build docker image for opendronemapd
  docker_image: 
    path: /opt/mambo/opendronemapd
    name: mambo/opendronemapd
    state: present
- name: Build docker image for gdal2tiles
  docker_image: 
    path: /opt/mambo/gdal2tiles
    name: mambo/gdal2tiles
    state: present
- name: Build docker image for mambo tile Api
  docker_image: 
    name: handmambo/tile-api
    state: present
- name: Build docker image for mambo dashboard Website
  docker_image: 
    name: handmambo/dashboard-www
    state: present
- name: Build docker image for mambo sensor Api
  docker_image: 
    name: handmambo/sensor-api
    state: present
- name: Assign rights to services
  file:
    path: /etc/systemd/system
    recurse: yes
    mode: 0755
- name: Disable SELinux
  selinux:
    policy: targeted
    state: disabled
- name: Make sure Mambo is running
  service: 
    name: mambo
    state: started 
    enabled: yes
